image: savoirfairelinux/lampd

cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    
make:
  tags:
    - docker-images-test
  stage: build
  before_script:
    - rm -rf $CI_PROJECT_DIR/src/drupal
  script:
    - drush make -y --translations=fr build-8.x.make $CI_PROJECT_DIR/src/drupal
    
install:
  services: 
    - mariadb:latest
  variables:
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  tags:
    - docker-images-test
  stage: build
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal
  script:
    - drush site-install standard --locale="fr" --db-url=mysql://root:$MYSQL_ROOT_PASSWORD@mariadb/$MYSQL_DATABASE -y
  after_script:
    - drush status

unittest:
  tags:
    - docker-images-test
  stage: test
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal/core
  script:
    - ../vendor/bin/phpunit --testsuite=unit
    
behat:
  tags:
    - docker-images-test
  stage: test
  script:
    - ls
  
backup:
  tags:
    - docker-images-test
  stage: deploy
  script:
    - ls
  artifacts:
    paths:
      - src/drupal
  when: manual

offline:
  tags:
    - docker-images-test
  stage: deploy
  script:
    - ls
  when: manual

rsync:
  tags:
    - docker-images-test
  stage: deploy
  script:
    - ls
  when: manual

updatedb:
  tags:
    - docker-images-test
  stage: deploy
  script:
    - ls
  when: manual

online:
  tags:
    - docker-images-test
  stage: deploy
  script: 
    - ls
  when: manual
