image: savoirfairelinux/lampd

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/src/drupal
    
make:
  tags:
    - docker-images-test
  stage: build
  before_script:
    - rm -rf $CI_PROJECT_DIR/src/drupal
  script:
    - drush make -y --translations=fr build-8.x.make $CI_PROJECT_DIR/src/drupal
    
install:
  services: 
    - mariadb:latest
  variables:
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  tags:
    - docker-images-test
  stage: build
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal
  script:
    - drush site-install standard --db-url=mysql://root:$MYSQL_ROOT_PASSWORD@mariadb/$MYSQL_DATABASE -y
    - drush status
    - drush sql-dump --gzip --result-file=../db_dump.sql"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    expire_in: '1 week'
    paths:
      - src/db_dump.sql

unittest:
  tags:
    - docker-images-test
  stage: test
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal/core
  script:
    - ../vendor/bin/phpunit --testsuite=unit
    
behat:
  tags:
    - docker-images-test
  stage: test
  script:
    - ls
  
backup:
  tags:
    - docker-images-test
  stage: deploy
  only: 
    - master
  script:
    - ls

offline:
  tags:
    - docker-images-test
  stage: deploy
  only: 
    - master
  script:
    - ls

rsync:
  tags:
    - docker-images-test
  stage: deploy
  only: 
    - master
  script:
    - ls

updatedb:
  tags:
    - docker-images-test
  stage: deploy
  only: 
    - master
  script:
    - ls

online:
  tags:
    - docker-images-test
  stage: deploy
  only: 
    - master
  script: 
    - ls
  when: manual
