image: savoirfairelinux/lampd

make:
  tags:
    - docker-images
  service: mysql
  script:
    - drush make -y --translations=fr build-8.x.make src/drupal
    - cd src/drupal
    - drush site-install standard --db-url=mysql://dev:dev@mysql/db_drupal -y