image: savoirfairelinux/lampd

stages: 
  - build

cache:
    key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
    untracked: true
    
make:
  tags:
    - docker-images-test
  stage: build
  script:
    - drush make -y --translations=fr build-8.x.make src/drupal
    
install:
  services: 
    - mariadb:latest
  tags:
    - docker-images-test
  stage: build
  variables:
    MYSQL_DATABASE: el_duderino
    MYSQL_ROOT_PASSWORD: EedaeJ5ewohghe9echah7ahJ
  script:
    - cd $CI_PROJECT_DIR/src/drupal
    - drush site-install standard --db-url=mysql://root:EedaeJ5ewohghe9echah7ahJ@mariadb/el_duderino -y