image: savoirfairelinux/lampd

stages: 
  - build
  - test

cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    
make:
  tags:
    - docker-images-test
  stage: build
  before_script:
    - rm -rf $CI_PROJECT_DIR/src/drupal
  script:
    - drush make -y --translations=fr build-8.x.make $CI_PROJECT_DIR/src/drupal
    
install:
  services: 
    - mariadb:latest
  tags:
    - docker-images-test
  stage: build
  script:
    - cd $CI_PROJECT_DIR/src/drupal
    - drush site-install standard --db-url=mysql://root:$MYSQL_ROOT_PASSWORD@mariadb/$MYSQL_DATABASE -y

test:
  tags:
    - docker-images-test
  stage: test
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal/core
  script:
    - ../vendor/bin/phpunit --testsuite=unit
    
  
  