image: savoirfairelinux/lampd

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/src/drupal
    
make:
  tags:
    - docker-generic
  stage: build
  before_script:
    - rm -rf $CI_PROJECT_DIR/src/drupal
  script:
    - drush make -y --translations=fr build-8.x.make $CI_PROJECT_DIR/src/drupal
  artifacts:
    name: "plateform_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    expire_in: '1 week'
    paths:
      - src/drupal
    
install:
  services: 
    - mariadb:latest
  variables:
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  tags:
    - docker-generic
  stage: build
  dependencies:
    - make
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal
  script:
    - drush site-install standard --db-url=mysql://root:$MYSQL_ROOT_PASSWORD@mariadb/$MYSQL_DATABASE -y
    - drush status
    - drush sql-dump --gzip --result-file=$CI_PROJECT_DIR/src/db_dump.sql
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    expire_in: '1 week'
    paths:
      - src/db_dump.sql.gz

unittest:
  tags:
    - docker-generic
  stage: test
  before_script:
    - cd $CI_PROJECT_DIR/src/drupal/core
  script:
    - ls -l
    - ls -l $CI_PROJECT_DIR/src
    - ls -l $CI_PROJECT_DIR
    - ../vendor/bin/phpunit --testsuite=unit
    
webtest:
  tags:
    - docker-generic
  services: 
    - mariadb:latest
  variables:
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  stage: test
  before_script:
    - zcat $CI_PROJECT_DIR/src/db_dump.sql.gz | mysql -hmariadb -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE
    - cd $CI_PROJECT_DIR/src/drupal/core
  script:
    - ../vendor/bin/phpunit --group Drupal
  
backup:
  tags:
    - docker-generic
  stage: deploy
  only: 
    - master
  script:
    - ls

offline:
  tags:
    - docker-generic
  stage: deploy
  only: 
    - master
  script:
    - ls

rsync:
  tags:
    - docker-generic
  stage: deploy
  only: 
    - master
  script:
    - ls

updatedb:
  tags:
    - docker-generic
  stage: deploy
  only: 
    - master
  script:
    - ls

online:
  tags:
    - docker-generic
  stage: deploy
  only: 
    - master
  script: 
    - ls
  when: manual
