image: savoirfairelinux/lampd

make:
  tags:
    - docker-images
  services: 
    - mariadb:latest
  variables:
    MYSQL_DATABASE: el_duderino
    MYSQL_ROOT_PASSWORD: EedaeJ5ewohghe9echah7ahJ
  script:
    - drush make -y --translations=fr build-8.x.make src/drupal
    - cd src/drupal
    - drush site-install standard --db-url=mysql://root:EedaeJ5ewohghe9echah7ahJ@mariadb/el_duderino -y